## Bandung Basin Hydrogeological Information Apps

Bandung Basin Hydrogeological Information Apps is a master thesis project of Muhammad Malik Ar Rahiem on his M.Sc program in Tropical Hydrogeology and Environmental Engineering (TropHEE) at TU Darmstadt, Germany. In this application, points and spatial information regarding geology, hydrogeology, and subsurface in Bandung, Indonesia, are compiled, digitised, and visualised in a web based geographical information system.

Excessive groundwater extraction is a major threat to the sustainability of groundwater management in Bandung Basin, Indonesia. Therefore, it is crucial for Bandung Basin to strengthen its groundwater management system, for example by developing more precise aquifers geometry model and real time extraction monitoring system. The challenge in developing aquifers geometry model is the lack of available well data. Of more than 2000 wells data that registered in the government, very less of that number are possible to be extracted because the data are scattered in several department. Moreover, well-archived dataset is only available in print. This is the main reason why developing a WebGIS platform for the visualization of hydrogeological information of Bandung Basin, matters.

This application compiles available well-data in Bandung Basin from several sources; government, publications, and thesis. The data are digitised and visualised in a WebGIS platform developed using open-source language R and utilising tens of packages available in R environment. There are three main functions of this application, namely: 1) Maps visualisation, 2) Well profiles visualisation, and 3) Cross-section visualisation. There are 189 wells and 4 maps available to explore. These maps are: geological map, hydrogeological map, groundwater basin map, and groundwater zonation map. In the well profiles and cross section visualisation, 3 information can be obtained: lithology, resistivity, and well screen placement. 

This application is meant to democratise subsurface data in Bandung Basin to encourage open data so that further research, especially on groundwater management can be taken place. This is also an effort to promote open science. The data that is being used in this application are provided for public in online repositories Github and so does the script code. This application of subsurface visualisation is expected to encourage open data, open science, and later further research on subsurface model development, especially on more transparent groundwater management.
